/* Prefijos telefónicos internacionales: código ISO, nombre y prefijo de marcación */
const COUNTRY_CODES = [
  { iso: 'ES', name: 'España', dial: '34' },
  { iso: 'AD', name: 'Andorra', dial: '376' },
  { iso: 'DE', name: 'Alemania', dial: '49' },
  { iso: 'AT', name: 'Austria', dial: '43' },
  { iso: 'BE', name: 'Bélgica', dial: '32' },
  { iso: 'BG', name: 'Bulgaria', dial: '359' },
  { iso: 'CY', name: 'Chipre', dial: '357' },
  { iso: 'HR', name: 'Croacia', dial: '385' },
  { iso: 'DK', name: 'Dinamarca', dial: '45' },
  { iso: 'SK', name: 'Eslovaquia', dial: '421' },
  { iso: 'SI', name: 'Eslovenia', dial: '386' },
  { iso: 'EE', name: 'Estonia', dial: '372' },
  { iso: 'FI', name: 'Finlandia', dial: '358' },
  { iso: 'FR', name: 'Francia', dial: '33' },
  { iso: 'GR', name: 'Grecia', dial: '30' },
  { iso: 'HU', name: 'Hungría', dial: '36' },
  { iso: 'IE', name: 'Irlanda', dial: '353' },
  { iso: 'IS', name: 'Islandia', dial: '354' },
  { iso: 'IT', name: 'Italia', dial: '39' },
  { iso: 'LV', name: 'Letonia', dial: '371' },
  { iso: 'LI', name: 'Liechtenstein', dial: '423' },
  { iso: 'LT', name: 'Lituania', dial: '370' },
  { iso: 'LU', name: 'Luxemburgo', dial: '352' },
  { iso: 'MT', name: 'Malta', dial: '356' },
  { iso: 'MC', name: 'Mónaco', dial: '377' },
  { iso: 'ME', name: 'Montenegro', dial: '382' },
  { iso: 'NO', name: 'Noruega', dial: '47' },
  { iso: 'NL', name: 'Países Bajos', dial: '31' },
  { iso: 'PL', name: 'Polonia', dial: '48' },
  { iso: 'PT', name: 'Portugal', dial: '351' },
  { iso: 'GB', name: 'Reino Unido', dial: '44' },
  { iso: 'CZ', name: 'República Checa', dial: '420' },
  { iso: 'RO', name: 'Rumanía', dial: '40' },
  { iso: 'SM', name: 'San Marino', dial: '378' },
  { iso: 'RS', name: 'Serbia', dial: '381' },
  { iso: 'SE', name: 'Suecia', dial: '46' },
  { iso: 'CH', name: 'Suiza', dial: '41' },
  { iso: 'UA', name: 'Ucrania', dial: '380' },
  { iso: 'RU', name: 'Rusia', dial: '7' },
  { iso: 'BY', name: 'Bielorrusia', dial: '375' },
  { iso: 'MD', name: 'Moldavia', dial: '373' },
  { iso: 'MK', name: 'Macedonia del Norte', dial: '389' },
  { iso: 'BA', name: 'Bosnia y Herzegovina', dial: '387' },
  { iso: 'AL', name: 'Albania', dial: '355' },
  { iso: 'XK', name: 'Kosovo', dial: '383' },
  { iso: 'US', name: 'Estados Unidos', dial: '1' },
  { iso: 'CA', name: 'Canadá', dial: '1' },
  { iso: 'MX', name: 'México', dial: '52' },
  { iso: 'GT', name: 'Guatemala', dial: '502' },
  { iso: 'BZ', name: 'Belice', dial: '501' },
  { iso: 'HN', name: 'Honduras', dial: '504' },
  { iso: 'SV', name: 'El Salvador', dial: '503' },
  { iso: 'NI', name: 'Nicaragua', dial: '505' },
  { iso: 'CR', name: 'Costa Rica', dial: '506' },
  { iso: 'PA', name: 'Panamá', dial: '507' },
  { iso: 'CU', name: 'Cuba', dial: '53' },
  { iso: 'DO', name: 'República Dominicana', dial: '1' },
  { iso: 'PR', name: 'Puerto Rico', dial: '1' },
  { iso: 'JM', name: 'Jamaica', dial: '1' },
  { iso: 'HT', name: 'Haití', dial: '509' },
  { iso: 'CO', name: 'Colombia', dial: '57' },
  { iso: 'VE', name: 'Venezuela', dial: '58' },
  { iso: 'EC', name: 'Ecuador', dial: '593' },
  { iso: 'PE', name: 'Perú', dial: '51' },
  { iso: 'BO', name: 'Bolivia', dial: '591' },
  { iso: 'CL', name: 'Chile', dial: '56' },
  { iso: 'AR', name: 'Argentina', dial: '54' },
  { iso: 'UY', name: 'Uruguay', dial: '598' },
  { iso: 'PY', name: 'Paraguay', dial: '595' },
  { iso: 'BR', name: 'Brasil', dial: '55' },
  { iso: 'GY', name: 'Guyana', dial: '592' },
  { iso: 'SR', name: 'Surinam', dial: '597' },
  { iso: 'MA', name: 'Marruecos', dial: '212' },
  { iso: 'DZ', name: 'Argelia', dial: '213' },
  { iso: 'TN', name: 'Túnez', dial: '216' },
  { iso: 'LY', name: 'Libia', dial: '218' },
  { iso: 'EG', name: 'Egipto', dial: '20' },
  { iso: 'ZA', name: 'Sudáfrica', dial: '27' },
  { iso: 'NG', name: 'Nigeria', dial: '234' },
  { iso: 'KE', name: 'Kenia', dial: '254' },
  { iso: 'ET', name: 'Etiopía', dial: '251' },
  { iso: 'GH', name: 'Ghana', dial: '233' },
  { iso: 'SN', name: 'Senegal', dial: '221' },
  { iso: 'CI', name: 'Costa de Marfil', dial: '225' },
  { iso: 'CM', name: 'Camerún', dial: '237' },
  { iso: 'AO', name: 'Angola', dial: '244' },
  { iso: 'MZ', name: 'Mozambique', dial: '258' },
  { iso: 'GQ', name: 'Guinea Ecuatorial', dial: '240' },
  { iso: 'CV', name: 'Cabo Verde', dial: '238' },
  { iso: 'CD', name: 'Rep. Dem. del Congo', dial: '243' },
  { iso: 'CG', name: 'Congo', dial: '242' },
  { iso: 'GA', name: 'Gabón', dial: '241' },
  { iso: 'ML', name: 'Malí', dial: '223' },
  { iso: 'NE', name: 'Níger', dial: '227' },
  { iso: 'TD', name: 'Chad', dial: '235' },
  { iso: 'RW', name: 'Ruanda', dial: '250' },
  { iso: 'TZ', name: 'Tanzania', dial: '255' },
  { iso: 'UG', name: 'Uganda', dial: '256' },
  { iso: 'ZM', name: 'Zambia', dial: '260' },
  { iso: 'ZW', name: 'Zimbabue', dial: '263' },
  { iso: 'NA', name: 'Namibia', dial: '264' },
  { iso: 'BW', name: 'Botsuana', dial: '267' },
  { iso: 'CN', name: 'China', dial: '86' },
  { iso: 'JP', name: 'Japón', dial: '81' },
  { iso: 'KR', name: 'Corea del Sur', dial: '82' },
  { iso: 'KP', name: 'Corea del Norte', dial: '850' },
  { iso: 'IN', name: 'India', dial: '91' },
  { iso: 'PK', name: 'Pakistán', dial: '92' },
  { iso: 'BD', name: 'Bangladés', dial: '880' },
  { iso: 'LK', name: 'Sri Lanka', dial: '94' },
  { iso: 'NP', name: 'Nepal', dial: '977' },
  { iso: 'AF', name: 'Afganistán', dial: '93' },
  { iso: 'IR', name: 'Irán', dial: '98' },
  { iso: 'IQ', name: 'Irak', dial: '964' },
  { iso: 'SA', name: 'Arabia Saudí', dial: '966' },
  { iso: 'AE', name: 'Emiratos Árabes Unidos', dial: '971' },
  { iso: 'QA', name: 'Catar', dial: '974' },
  { iso: 'KW', name: 'Kuwait', dial: '965' },
  { iso: 'BH', name: 'Baréin', dial: '973' },
  { iso: 'OM', name: 'Omán', dial: '968' },
  { iso: 'JO', name: 'Jordania', dial: '962' },
  { iso: 'LB', name: 'Líbano', dial: '961' },
  { iso: 'SY', name: 'Siria', dial: '963' },
  { iso: 'IL', name: 'Israel', dial: '972' },
  { iso: 'PS', name: 'Palestina', dial: '970' },
  { iso: 'TR', name: 'Turquía', dial: '90' },
  { iso: 'YE', name: 'Yemen', dial: '967' },
  { iso: 'KZ', name: 'Kazajistán', dial: '7' },
  { iso: 'UZ', name: 'Uzbekistán', dial: '998' },
  { iso: 'TM', name: 'Turkmenistán', dial: '993' },
  { iso: 'TJ', name: 'Tayikistán', dial: '992' },
  { iso: 'KG', name: 'Kirguistán', dial: '996' },
  { iso: 'MN', name: 'Mongolia', dial: '976' },
  { iso: 'VN', name: 'Vietnam', dial: '84' },
  { iso: 'TH', name: 'Tailandia', dial: '66' },
  { iso: 'KH', name: 'Camboya', dial: '855' },
  { iso: 'LA', name: 'Laos', dial: '856' },
  { iso: 'MM', name: 'Myanmar', dial: '95' },
  { iso: 'MY', name: 'Malasia', dial: '60' },
  { iso: 'SG', name: 'Singapur', dial: '65' },
  { iso: 'ID', name: 'Indonesia', dial: '62' },
  { iso: 'PH', name: 'Filipinas', dial: '63' },
  { iso: 'BN', name: 'Brunéi', dial: '673' },
  { iso: 'TL', name: 'Timor Oriental', dial: '670' },
  { iso: 'AU', name: 'Australia', dial: '61' },
  { iso: 'NZ', name: 'Nueva Zelanda', dial: '64' },
  { iso: 'FJ', name: 'Fiyi', dial: '679' },
  { iso: 'PG', name: 'Papúa Nueva Guinea', dial: '675' }
];

function isoToFlagEmoji(iso) {
  return iso
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}
